replicaCount: 

resources:
  requests:
    cpu: 40m
    memory: 40M

ingress:
  hosts:
    - host: just-testing-dev.azurelaboratory.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: just-testing-dev-tls
      hosts:
        - just-testing-dev.azurelaboratory.com