replicaCount: 1
image:
  repository: rodstewart/just-testing
  pullPolicy: Always
  tag: just-testing-dev-latest
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""
service:
  type: ClusterIP
  port: 5000
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  enabled: true
  className: "nginx"
  hosts:
    - host: just-testing-dev.azurelaboratory.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: just-testing-tls
      hosts:
        - just-testing-dev.azurelaboratory.com
livenessProbe:
  httpGet:
    path: /api/v1/healthz
    port: http
readinessProbe:
  httpGet:
    path: /api/v1/healthz
    port: http
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
resources:
  requests:
    cpu: 50m
    memory: 50M
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
